SUBGROUP_LEADER_TITLE = 'Subgroup Leader'
GROUP_LEADER_TITLE = 'Group Leader'
DEPARTMENT_LEADER_TITLE = 'Department Leader'
MEMBER_TITLE = 'Member'

YG = 'YG'
WG = 'WG'
MG = 'MG'
SG = 'SG'
UNREGISTERED = 'Unregistered'
