# Generated by Django 4.1.7 on 2023-03-29 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_remove_member_department'),
        ('reports', '0002_report_created_report_type_alter_report_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='structure.member'),
        ),
    ]
