# Generated by Django 4.1.7 on 2023-03-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_id',
        ),
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, choices=[('lesson', 'Lesson'), ('activity', 'Activity'), ('homework', 'Homework'), ('weekly-meeting', 'Weekly Meeting')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(blank=True, choices=[('attendance', 'Attendance'), ('participation', 'Participation')], max_length=50, null=True),
        ),
    ]
