# Generated by Django 4.1.7 on 2023-03-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_report_id_alter_report_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, choices=[('lesson', 'Lesson'), ('activity', 'Activity'), ('homework', 'Homework'), ('weekly_meeting', 'Weekly Meeting')], max_length=50, null=True),
        ),
    ]
