# Generated by Django 4.1.7 on 2023-03-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_report_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='type',
        ),
    ]
