# Generated by Django 4.1.7 on 2023-03-30 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='text_value',
        ),
    ]
