# Generated by Django 4.1.7 on 2023-04-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_remove_report_text_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
