# Generated by Django 4.1.7 on 2023-04-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_report_created_alter_report_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='value',
            field=models.BooleanField(blank=True),
        ),
    ]
