# Generated by Django 4.1.7 on 2023-04-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_report_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(blank=True, choices=[('lesson', 'Lesson'), ('activity', 'Activity'), ('homework', 'Homework'), ('weekly_meeting', 'weekly_meeting')], max_length=50, null=True),
        ),
    ]
