# Generated by Django 4.1.7 on 2023-04-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_delete_group'),
        ('reports', '0012_report_day_alter_report_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='report',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('name', 'member', 'report_date')},
        ),
        migrations.RemoveField(
            model_name='report',
            name='day',
        ),
    ]
