# Generated by Django 4.1.7 on 2023-04-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_delete_group'),
        ('reports', '0013_alter_report_unique_together_report_report_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('name', 'member', 'updated')},
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_date',
        ),
    ]
