# Generated by Django 4.1.7 on 2023-04-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_delete_group'),
        ('reports', '0014_alter_report_unique_together_alter_report_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='updated',
            new_name='report_date',
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('name', 'member', 'report_date')},
        ),
    ]
