# Generated by Django 4.1.7 on 2023-05-02 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_department_is_deleted_member_is_deleted_and_more'),
        ('reports', '0015_rename_updated_report_report_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='member',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='structure.member'),
        ),
    ]
