services:
  api:
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    command: python manage.py runserver
    volumes:
      - ./backend.:/backend

  web:
    restart: always
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    command: npm start
    volumes:
        - ./frontend.:/frontend