# Generated by Django 4.1.7 on 2023-03-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_remove_department_nickname_remove_subgroup_nickname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='nickname',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='nickname',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
    ]
