# Generated by Django 4.1.7 on 2023-04-05 12:29

import backend.structure.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_rename_nickname_member_underscore_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='subgroup',
            field=models.ForeignKey(default=backend.structure.models.get_default_subgroup, on_delete=django.db.models.deletion.PROTECT, to='structure.subgroup'),
        ),
        migrations.AlterField(
            model_name='subgroup',
            name='department',
            field=models.ForeignKey(default=backend.structure.models.get_default_department, on_delete=django.db.models.deletion.PROTECT, to='structure.department'),
        ),
    ]
