# Generated by Django 4.1.7 on 2023-04-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0008_alter_member_subgroup_alter_subgroup_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.CharField(blank=True, default='YG', max_length=45, null=True),
        ),
    ]
