# Generated by Django 4.1.7 on 2023-04-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0009_alter_member_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
