# Generated by Django 4.1.7 on 2023-05-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0010_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
