# Generated by Django 4.1.7 on 2023-05-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0011_department_is_deleted_member_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_leader',
        ),
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='subgroup_leader',
        ),
    ]
