# Generated by Django 4.1.7 on 2023-03-26 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_leader',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.RemoveField(
            model_name='member',
            name='department',
        ),
        migrations.RemoveField(
            model_name='member',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subgroup',
            name='subgroup_leader',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='SubGroup',
        ),
    ]
