# Generated by Django 4.1.7 on 2023-03-26 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=110, null=True)),
                ('report_id', models.IntegerField()),
                ('updated', models.DateField(auto_now=True)),
                ('value', models.BooleanField(blank=True, default=False)),
                ('text_value', models.CharField(blank=True, max_length=110, null=True)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_member', to='structure.member')),
            ],
        ),
    ]
